version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/myapp

hooks:
  BeforeInstall:
    - location: scripts/uninstall_dependencies.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root
      # This script includes 'npm install' to install node modules

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
      runas: root
      # This script should include 'npm start' to start your Node.js application

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 180
      runas: root
