name: Node.js CI

# Trigger this workflow on pushes to the 'main' branch and on pull requests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # You can adjust this to match your Node.js version

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment based on the matrix defined
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the linter
      - name: Run ESLint
        run: npm run lint

      # Run the application (This is optional in CI, but added for testing in dev mode)
      - name: Run the app
        run: npm run dev
        env:
          NODE_ENV: development

      # Run tests (You don't have tests defined yet)
      - name: Test Application
        run: |
          echo "No tests available"

      # Upload Node.js build artifacts (optional, if you need to keep any)
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nodejs-build
          path: .
