name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Use Node.js 18.x for your project

    steps:
      # Checkout the repository (This will use Node.js 20 as per GitHub's internal policy)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment for your project (specifically Node.js 18.x)
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint to check code quality
      - name: Run ESLint
        run: npm run lint

      # Run the application (optional in CI, mainly for testing in dev mode)
      - name: Run the app
        run: npm run dev
        env:
          NODE_ENV: development

      # Test application (if you had tests defined, they'd go here)
      - name: Test Application
        run: |
          echo "No tests available"

      # Optional: Upload any build artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nodejs-build
          path: .
