name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache npm dependencies
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Set up Node.js environment for your project
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install project dependencies using npm ci
      - name: Install dependencies
        run: npm ci

      # Debugging: Check current directory and list files
      - name: Show current directory
        run: pwd

      - name: List files in directory
        run: ls -la

      # Run ESLint to check code quality (optional)
      # - name: Lint code with ESLint
      #   run: npm run lint

      # Run the application with verbose output
      - name: Run the app
        run: npm run build --verbose

      # Test application (if you had tests defined, they'd go here)
      - name: Test Application
        run: |
          echo "No tests available"

      # Optional: Upload any build artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nodejs-build
          path: .
