name: Start Node.js Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  start-app:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Adjust this to match your project's Node.js version requirement

    - name: Install Dependencies
      run: npm install

    - name: Start Application
      run: npm start &
      timeout-minutes: 1  # Runs the application for 1 minute to ensure it starts without errors
