name: Node.js CI/CD to EC2

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  build-and-deploy:
    # Use self-hosted runner instead of GitHub-hosted runner
    runs-on: self-hosted  # This will run on your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Make sure you have a test script in your package.json

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Rsync project files
      run: rsync -av --exclude='.git*' --exclude='node_modules' ./ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/nodeapp

    - name: Install production dependencies and restart application
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          cd /var/www/nodeapp
          npm install --production
          pm2 restart all || pm2 start npm --name "nodeapp" -- start
        EOF
